### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by CodeDoctorDE** [DRE2N/ItemsXL#10]
```[06:27:26 INFO]: [ItemsXL] Enabling ItemsXL v0.5.5
[06:27:26 INFO]: [##########[ItemsXL]##########]
[06:27:26 INFO]: Internals: [v1_14_R1]
[06:27:26 INFO]: Spigot API: [true]
[06:27:26 INFO]: Paper API: [true]
[06:27:26 INFO]: Economy: [false]
[06:27:26 INFO]: Permissions: [false]
[06:27:26 INFO]: Metrics: [https://bstats.org/plugin/bukkit/ItemsXL]
[06:27:26 INFO]: SpigotMC ID: [14472]
[06:27:26 INFO]: [###############################]
[06:27:26 ERROR]: Error occurred while enabling ItemsXL v0.5.5 (Is it up to date?)
java.lang.NullPointerException: null
	at de.erethon.caliburn.item.CustomItem.register(CustomItem.java:337) ~[?:?]
	at de.erethon.itemsxl.ItemsXL.loadItems(ItemsXL.java:193) ~[?:?]
	at de.erethon.itemsxl.ItemsXL.loadAPI(ItemsXL.java:137) ~[?:?]
	at de.erethon.itemsxl.ItemsXL.onEnable(ItemsXL.java:68) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-146]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-146]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-146]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[06:27:26 INFO]: [ItemsXL] Disabling ItemsXL v0.5.5
```
Version: 1.14.4
I have no custom items and mobs!

**Comment by Sataniel98** [comment]
It says there is a file in the custom items folder though.

**Comment by CodeDoctorDE** [comment]
oh i didn't see it. https://hastebin.com/eluzoxeyil.makefile

**Comment by CodeDoctorDE** [comment]
it's the default file in the wiki

**Comment by Sataniel98** [comment]
How is that file called?

**Comment by CodeDoctorDE** [comment]
EMERALD_SWORD.yml
