### ISSUE TITLE
Custom Items sample

### ISSUE THREAD

**Issue by zykool** [DRE2N/ItemsXL#14]
Could you make a sample to show how to create a custom items？
I want use it for DXL required items.

**Comment by Sataniel98** [comment]
There's one in the wiki: https://github.com/DRE2N/CaliburnAPI/wiki/custom-item-script

**Comment by zykool** [comment]
Yes I seen this.

But When I copy this into the custom items folder as test.yml .
There will be an error: 
`[04:16:22 WARN]: Unexpected exception while parsing console command "IXL"
org.bukkit.command.CommandException: Cannot execute command 'ixl' in plugin ItemsXL v0.5.5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

[04:16:45 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ixl' in plugin ItemsXL v0.5.5 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_221]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[%e7%a4%be%e5%8c%ba2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
`

**Comment by HikkaKun** [comment]
Same problem
