### ISSUE TITLE
Exception whild loading ItemsXL on Spigot 1.12.1 / PaperSpigot 1.12/1.12.1

### ISSUE THREAD

**Issue by k-jiang** [DRE2N/ItemsXL#7]
```
[07:25:22] [Server thread/INFO]: [ItemsXL] Enabling ItemsXL v0.2.5
[07:25:22] [Server thread/INFO]: [##########[ItemsXL]##########]
[07:25:22] [Server thread/INFO]: Internals: [v1_12_R1]
[07:25:22] [Server thread/INFO]: Spigot API: [true]
[07:25:22] [Server thread/INFO]: UUIDs: [true]
[07:25:22] [Server thread/INFO]: Economy: [false]
[07:25:22] [Server thread/INFO]: Permissions: [false]
[07:25:22] [Server thread/INFO]: Metrics: [true]
[07:25:22] [Server thread/INFO]: SpigotMC ID: [14472]
[07:25:22] [Server thread/INFO]: [###############################]
[07:25:22] [Server thread/INFO]: An error occurred while accessing the handler class of the item type CUSTOM_DEFAULT: InvocationTargetException
[07:25:22] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[07:25:22] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[07:25:22] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[07:25:22] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:25:22] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.caliburn.item.ItemType.instantiate(ItemType.java:60)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.caliburn.item.Items.addItem(Items.java:100)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.itemsxl.ItemsXL.loadItems(ItemsXL.java:229)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.itemsxl.ItemsXL.loadAPI(ItemsXL.java:168)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.itemsxl.ItemsXL.onEnable(ItemsXL.java:83)
[07:25:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[07:25:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[07:25:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[07:25:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376)
[07:25:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325)
[07:25:22] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441)
[07:25:22] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402)
[07:25:22] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340)
[07:25:22] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290)
[07:25:22] [Server thread/WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[07:25:22] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:25:22] [Server thread/WARN]: Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.caliburn.item.CustomItem.<init>(CustomItem.java:120)
[07:25:22] [Server thread/WARN]:        at io.github.dre2n.caliburn.item.CustomItem.<init>(CustomItem.java:144)
[07:25:22] [Server thread/WARN]:        ... 20 more
```

Tested on:
Environment 1: Spigot 1.12.1 build 1384
Environment 2: PaperSpigot 1.12 build 1169
Environment 3: PaperSpigot 1.12.1 build build 1178

Both ItemsXL 0.2.5 and 0.3 are failed.

p.s. download any of the dev builds from your server returns an 404. http://feuerstern.bplaced.net/repo/io/github/dre2n/itemsxl/

**Comment by Sataniel98** [comment]
Your item script is erroneous. Dev builds aren't necessary for ItemsXL at the moment.

**Comment by Sataniel98** [comment]
I'm closing this because of the massive changes since 0.2.5
